In [38]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
df = pd.read_csv('Titanic.csv')

In [39]:
df.drop('Ticket', axis =1)
x = df.drop('Survived', axis =1)
y = df['Survived']

In [40]:
x

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [41]:
from sklearn.preprocessing import MinMaxScaler
num_cols = x.select_dtypes("number").columns
Scaler = MinMaxScaler()
Scaler.fit(x[num_cols])
x[num_cols] = Scaler.transform(x[num_cols])

In [42]:
x

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0.000000,1.0,"Braund, Mr. Owen Harris",male,0.271174,0.125,0.000000,A/5 21171,0.014151,NaN,S
1,0.001124,0.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.472229,0.125,0.000000,PC 17599,0.139136,C85,C
2,0.002247,1.0,"Heikkinen, Miss. Laina",female,0.321438,0.000,0.000000,STON/O2. 3101282,0.015469,NaN,S
3,0.003371,0.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.434531,0.125,0.000000,113803,0.103644,C123,S
4,0.004494,1.0,"Allen, Mr. William Henry",male,0.434531,0.000,0.000000,373450,0.015713,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
886,0.995506,0.5,"Montvila, Rev. Juozas",male,0.334004,0.000,0.000000,211536,0.025374,NaN,S
887,0.996629,0.0,"Graham, Miss. Margaret Edith",female,0.233476,0.000,0.000000,112053,0.058556,B42,S
888,0.997753,1.0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,0.125,0.333333,W./C. 6607,0.045771,NaN,S
889,0.998876,0.0,"Behr, Mr. Karl Howell",male,0.321438,0.000,0.000000,111369,0.058556,C148,C
890,1.000000,1.0,"Dooley, Mr. Patrick",male,0.396833,0.000,0.000000,370376,0.015127,NaN,Q

In [ ]:
#!pip install category_encoders
str_cols = x.select_dtypes('str').columns
str_cols= ['Sex',"Embarked"]

In [ ]:
from category_encoders import OneHotEncoder
str_cols= ["Sex", "Embarked"] #x.select_dtypes("string").columns
encoder = OneHotEncoder(cols = str_cols, drop_invariant=True)
x = encoder.fit_transform(x)
x

,PassengerId,Pclass,Name,Sex_1,Sex_2,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_1,Embarked_2,Embarked_3,Embarked_4
0,0.000000,1.0,"Braund, Mr. Owen Harris",1,0,0.271174,0.125,0.000000,A/5 21171,0.014151,NaN,1,0,0,0
1,0.001124,0.0,"Cumings, Mrs. John Bradley (Florence Briggs Th...",0,1,0.472229,0.125,0.000000,PC 17599,0.139136,C85,0,1,0,0
2,0.002247,1.0,"Heikkinen, Miss. Laina",0,1,0.321438,0.000,0.000000,STON/O2. 3101282,0.015469,NaN,1,0,0,0
3,0.003371,0.0,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",0,1,0.434531,0.125,0.000000,113803,0.103644,C123,1,0,0,0
4,0.004494,1.0,"Allen, Mr. William Henry",1,0,0.434531,0.000,0.000000,373450,0.015713,NaN,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0.995506,0.5,"Montvila, Rev. Juozas",1,0,0.334004,0.000,0.000000,211536,0.025374,NaN,1,0,0,0
887,0.996629,0.0,"Graham, Miss. Margaret Edith",0,1,0.233476,0.000,0.000000,112053,0.058556,B42,1,0,0,0
888,0.997753,1.0,"Johnston, Miss. Catherine Helen ""Carrie""",0,1,NaN,0.125,0.333333,W./C. 6607,0.045771,NaN,1,0,0,0
889,0.998876,0.0,"Behr, Mr. Karl Howell",1,0,0.321438,0.000,0.000000,111369,0.058556,C148,0,1,0,0
890,1.000000,1.0,"Dooley, Mr. Patrick",1,0,0.396833,0.000,0.000000,370376,0.015127,NaN,0,0,1,0

linkedin post about our work & projects
-listen to recording that will be sent and apply it. (assignment)