Data preprocessing
step 1 - data understanding / business understanding
titanic dataset--used to study data science in most courses
steps:
1- read data
2- check dtypes [data may have dependency:??]
3- handle dtype 
4- check nulls
5- handling nulls
6- check outliers
7- handling outliers
8- check duplicated
9- handling duplicated
10- data visualization
    Machine learning starts here:
11- data splitting [??]
12- Normalization [task coming about this, scaling of data, smoothing]
13- encoding

In [6]:
import pandas as pd

In [7]:
df = pd.read_csv('Titanic.csv')

In [8]:
DROP_COLS = ["PassengerId",
             "Name",
             "Ticket"]
def drop_cols(df: pd.DataFrame, cols: list[str])->pd.DataFrame:
    return df.drop(columns=cols)

In [9]:
drop_cols(df, DROP_COLS)

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0           0       3    male  22.0      1      0   7.2500   NaN        S
1           1       1  female  38.0      1      0  71.2833   C85        C
2           1       3  female  26.0      0      0   7.9250   NaN        S
3           1       1  female  35.0      1      0  53.1000  C123        S
4           0       3    male  35.0      0      0   8.0500   NaN        S
..        ...     ...     ...   ...    ...    ...      ...   ...      ...
886         0       2    male  27.0      0      0  13.0000   NaN        S
887         1       1  female  19.0      0      0  30.0000   B42        S
888         0       3  female   NaN      1      2  23.4500   NaN        S
889         1       1    male  26.0      0      0  30.0000  C148        C
890         0       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 9 columns]

In [3]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

drop columns that we don't need

In [12]:
df.drop(["PassengerId","Name","Ticket"], axis=1, inplace=True) #axis = 1 means i'm dropping columns, axis = 0 i'm dropping rows, inplace=true means ...

In [13]:
df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

checking dtype & handling dtype
limited ..descrete..categorical
big numbers ..continuous

In [15]:
dtype = df.dtypes
n_uniq = df.nunique()
pd.DataFrame({"Dtype ":dtype, "N_unique ": n_uniq}).T

          Survived Pclass  Sex      Age  SibSp  Parch     Fare Cabin Embarked
Dtype        int64  int64  str  float64  int64  int64  float64   str      str
N_unique         2      3    2       88      7      7      248   147        3

In [16]:
cols = ["Survived","Pclass","Sex","SibSp","Parch","Embarked"]
df[cols] = df[cols].astype("category")
pd.DataFrame(df.dtypes).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
0,category,category,category,float64,category,category,float64,str,category

In [ ]:
def get_data_summary(df):
    return pd.DataFrame({"Dtype ":df.dtype, "N_unique ": df.n_uniq}).T

handle null values
if most values existed and null is around 20% can fill the missing values using the historical data
if numerical col (and has outliers, noise) then use median instead of mean to fill the missing values
if col is string use mode to fill the missing values

In [18]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Survived  891 non-null    category
 1   Pclass    891 non-null    category
 2   Sex       891 non-null    category
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    category
 5   Parch     891 non-null    category
 6   Fare      891 non-null    float64
 7   Cabin     204 non-null    str
 8   Embarked  889 non-null    category
dtypes: category(6), float64(2), str(1)
memory usage: 26.7 KB

In [22]:
null = df.isnull().sum()
ratio = (null / df.shape[0])*100
pd.DataFrame({"null ":null, "ratio ": ratio}).T

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Cabin,Embarked
null,0.0,0.0,0.0,177.00000,0.0,0.0,0.0,687.000000,2.000000
ratio,0.0,0.0,0.0,19.86532,0.0,0.0,0.0,77.104377,0.224467

In [ ]:
df = df.dropna(subset=['Embarked']) #droped rows with nulls in the column embarked

In [30]:
null = df.isnull().sum()
ratio = (null / df.shape[0])*100
pd.DataFrame({"null ":null, "ratio ": ratio}).T

        Survived  Pclass  Sex  Age  SibSp  Parch  Fare  Embarked
null         0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0
ratio        0.0     0.0  0.0  0.0    0.0    0.0   0.0       0.0

In [25]:
df = df.drop("Cabin", axis=1)

In [29]:
#df.describe()   
median = df['Age'].median()
df['Age'] = df['Age'].fillna(median, inplace=True)

C:\Users\newle\AppData\Local\Temp\ipykernel_35288\286410004.py:3: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Age'] = df['Age'].fillna(median, inplace=True)

check outliers

In [39]:
num_cols = df.select_dtypes("number").columns
for col in num_cols:
    Q1 = df[col].quantile(.25)
    Q3 = df[col].quantile(0.75)
    #print(Q1,Q3)
    IQR = Q3 - Q1
    lower_fence = Q1 - 1.5*IQR
    upper_fence = Q3 - 1.5*IQR
    print(lower_fence)
    lower_outliers = df[df[col] < lower_fence][col].values
    print(lower_outliers)
    upper_outliers = df[df[col] > upper_fence][col].values
    #print(upper_outliers)

2.5
[2.   2.   0.83 2.   1.   1.   1.   2.   2.   0.92 2.   1.   1.   0.75
 2.   2.   2.   0.75 0.67 1.   0.42 2.   1.   0.83]
-26.7605
[]

In [33]:
df.describe()

              Age        Fare
count  889.000000  889.000000
mean    29.315152   32.096681
std     12.984932   49.697504
min      0.420000    0.000000
25%     22.000000    7.895800
50%     28.000000   14.454200
75%     35.000000   31.000000
max     80.000000  512.329200